### ISSUE TITLE
(*) Балансировка дерева

### ISSUE THREAD

**Issue by avasyukov** [Hrach2000/Tree#2]
Если попробовать заполнить дерево банально вот так:
```c++
int main()
{
  Container* c = new Tree();
  for(int i = 1; i < 10; i++)
    c->insert(i*i);

  cout << "Tree after creation:" << endl;
  c->print();

  delete c;
  return 0;
}
```
и при этом напечатать подробностей про узлы вот таким образом:
```c++

    cout << "Element: " << root->key << " ";

    if(root->right != nullptr)
      cout << "Right: " << root->right->key << " ";
    else
      cout << "Right: -- ";

    if(root->left != nullptr)
      cout << "Left: " << root->left->key << " ";
    else
      cout << "Left: -- ";

    cout << endl;
```
то видно, что дерево корректно, но без баланса:
```
Tree after creation:
Element: 25 Right: 64 Left: 1 
Element: 1 Right: 16 Left: -- 
Element: 16 Right: -- Left: 9 
Element: 9 Right: -- Left: 4 
Element: 4 Right: -- Left: -- 
Element: 64 Right: 81 Left: 49 
Element: 49 Right: -- Left: 36 
Element: 36 Right: -- Left: -- 
Element: 81 Right: -- Left: -- 
```

**Comment by Hrach2000** [comment]
У меня используется балансировка декартова дерева. Добавил тесты(в main.cpp) При 10^6 узлах высота - 49, а при 10^5 - 42. Легко видеть, что скорость возрастания логарифмическая

**Comment by avasyukov** [comment]
Понял. Мои извинения - глаз замылен. Посмотрю ещё раз.

**Comment by avasyukov** [comment]
Посмотрел ещё раз. Оно у Вас получается "примерно сбалансированное". В строгом смысле сбалансированное дерево это всё же когда: 
> для каждой вершины высота её двух поддеревьев различается не более чем на 1

Из этого сразу следует, что в дерево высоты N умещается (2^N - 1) узлов. Плюс следует, что пока элементов в дереве не более чем (2^N - 1), слой (N+1) заполняться не начинает.

Сейчас у Вас вроде балансировка есть - 10^6 элементов укладывается в 49 слоёв узлов и т.д. Но при этом на малом количестве узлов (когда все связи можно отследить глазами) видно, что строгой сбалансированности нет - например, для 7 узлов высота получается 5 (не 7, ок), хотя достаточно дерева высоты 3 для размещения всех узлов.

Вопрос: это баг или фича? Такое поведение ожидается? Если ожидается - ок, но поясните логику балансировки.

**Comment by Hrach2000** [comment]
Логика в том, что дерево балансируется и по ключу, и по случайному приоритету. При такой балансировке, можно показать, что математическое ожидание высоты будет log(n).

**Comment by avasyukov** [comment]
Ответ норм. Сдано.
